/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.ApiClient;
import org.openapitools.client.model.AddRulesRequest;
import org.openapitools.client.model.DeleteRulesRequest;
import org.openapitools.client.model.DeleteRulesRequestDelete;
import org.openapitools.client.model.RuleNoId;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddOrDeleteRulesRequest
 */
public class AddOrDeleteRulesRequestTest {
    private final AddOrDeleteRulesRequest model = new AddOrDeleteRulesRequest();

    /**
     * Model tests for AddOrDeleteRulesRequest
     */
    @Test
    public void testAddOrDeleteRulesRequest() {
        ApiClient apiClient = new ApiClient();
        AddOrDeleteRulesRequest r = new AddOrDeleteRulesRequest();
        AddRulesRequest add = new AddRulesRequest();
        RuleNoId rule = new RuleNoId();
        rule.setValue("Blue");
        add.addAddItem(rule);
        r.setActualInstance(add);
        //AddOrDeleteRulesResponse result = apiInstance.addOrDeleteRules(r, false);
        Assert.assertEquals(apiClient.getJSON().getGson().toJson(r), "{\"add\":[{\"value\":\"Blue\"}]}");
    }

    /**
     * Test the property 'add'
     */
    @Test
    public void addTest() {
        // TODO: test add
    }

    /**
     * Test the property 'delete'
     */
    @Test
    public void deleteTest() {
        // TODO: test delete
    }

}
