/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject2
 */
public class InlineObject2Test {
    private final InlineObject2 model = new InlineObject2();

    /**
     * Model tests for InlineObject2
     */
    @Test
    public void testInlineObject2() {
        // TODO: test InlineObject2
    }

    /**
     * Test the property 'targetUserId'
     */
    @Test
    public void targetUserIdTest() {
        // TODO: test targetUserId
    }

}
