/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2002Meta
 */
public class InlineResponse2002MetaTest {
    private final InlineResponse2002Meta model = new InlineResponse2002Meta();

    /**
     * Model tests for InlineResponse2002Meta
     */
    @Test
    public void testInlineResponse2002Meta() {
        // TODO: test InlineResponse2002Meta
    }

    /**
     * Test the property 'previousToken'
     */
    @Test
    public void previousTokenTest() {
        // TODO: test previousToken
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'resultCount'
     */
    @Test
    public void resultCountTest() {
        // TODO: test resultCount
    }

}
