/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Model2TweetsGeo;
import org.openapitools.client.model.Model2TweetsMedia;
import org.openapitools.client.model.Model2TweetsPoll;
import org.openapitools.client.model.Model2TweetsReply;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject3
 */
public class InlineObject3Test {
    private final InlineObject3 model = new InlineObject3();

    /**
     * Model tests for InlineObject3
     */
    @Test
    public void testInlineObject3() {
        // TODO: test InlineObject3
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'directMessageDeepLink'
     */
    @Test
    public void directMessageDeepLinkTest() {
        // TODO: test directMessageDeepLink
    }

    /**
     * Test the property 'quoteTweetId'
     */
    @Test
    public void quoteTweetIdTest() {
        // TODO: test quoteTweetId
    }

    /**
     * Test the property 'forSuperFollowersOnly'
     */
    @Test
    public void forSuperFollowersOnlyTest() {
        // TODO: test forSuperFollowersOnly
    }

    /**
     * Test the property 'reply'
     */
    @Test
    public void replyTest() {
        // TODO: test reply
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'poll'
     */
    @Test
    public void pollTest() {
        // TODO: test poll
    }

    /**
     * Test the property 'replySettings'
     */
    @Test
    public void replySettingsTest() {
        // TODO: test replySettings
    }

    /**
     * Test the property 'geo'
     */
    @Test
    public void geoTest() {
        // TODO: test geo
    }

}
