/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Model2TweetsGeo
 */
public class Model2TweetsGeoTest {
    private final Model2TweetsGeo model = new Model2TweetsGeo();

    /**
     * Model tests for Model2TweetsGeo
     */
    @Test
    public void testModel2TweetsGeo() {
        // TODO: test Model2TweetsGeo
    }

    /**
     * Test the property 'placeId'
     */
    @Test
    public void placeIdTest() {
        // TODO: test placeId
    }

}
