/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Model2TweetsReply
 */
public class Model2TweetsReplyTest {
    private final Model2TweetsReply model = new Model2TweetsReply();

    /**
     * Model tests for Model2TweetsReply
     */
    @Test
    public void testModel2TweetsReply() {
        // TODO: test Model2TweetsReply
    }

    /**
     * Test the property 'inReplyToTweetId'
     */
    @Test
    public void inReplyToTweetIdTest() {
        // TODO: test inReplyToTweetId
    }

    /**
     * Test the property 'excludeReplyUserIds'
     */
    @Test
    public void excludeReplyUserIdsTest() {
        // TODO: test excludeReplyUserIds
    }

}
