/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Model2TweetsMedia
 */
public class Model2TweetsMediaTest {
    private final Model2TweetsMedia model = new Model2TweetsMedia();

    /**
     * Model tests for Model2TweetsMedia
     */
    @Test
    public void testModel2TweetsMedia() {
        // TODO: test Model2TweetsMedia
    }

    /**
     * Test the property 'mediaIds'
     */
    @Test
    public void mediaIdsTest() {
        // TODO: test mediaIds
    }

    /**
     * Test the property 'taggedUserIds'
     */
    @Test
    public void taggedUserIdsTest() {
        // TODO: test taggedUserIds
    }

}
