/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.34
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ComplianceJobStatus;
import org.openapitools.client.model.ComplianceJobType;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.InlineObject5;
import org.openapitools.client.model.MultiComplianceJobResponse;
import org.openapitools.client.model.Problem;
import org.openapitools.client.model.SingleComplianceJobResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ComplianceApi
 */
@Ignore
public class ComplianceApiTest {

    private final ComplianceApi api = new ComplianceApi();

    
    /**
     * Create compliance job
     *
     * Creates a compliance for the given job type
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBatchComplianceJobTest() throws ApiException {
        InlineObject5 inlineObject5 = null;
                SingleComplianceJobResponse response = api.createBatchComplianceJob(inlineObject5);
        // TODO: test validations
    }
    
    /**
     * Get compliance job
     *
     * Returns a single compliance job by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBatchComplianceJobTest() throws ApiException {
        String id = null;
                SingleComplianceJobResponse response = api.getBatchComplianceJob(id);
        // TODO: test validations
    }
    
    /**
     * List compliance jobs
     *
     * Returns recent compliance jobs for a given job type and optional job status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBatchComplianceJobsTest() throws ApiException {
        ComplianceJobType type = null;
        ComplianceJobStatus status = null;
                MultiComplianceJobResponse response = api.listBatchComplianceJobs(type, status);
        // TODO: test validations
    }
    
}
